### ISSUE TITLE
support inter_contract_call_operation and trust_node_pledge_withdraw_operation

### ISSUE THREAD

**Issue by zhuliting** [gxchain/gxchain-light#17]
support the following 3 operation history:

- inter_contract_call_operation history:
```
op id: 79
https://testnet.wallet.gxchain.org/#/account/va7/overview/
```

-  trust_node_pledge_withdraw_operation history:
```
op id: 77
https://testnet.wallet.gxchain.org/#/account/good1/overview

block: https://testnet.wallet.gxchain.org/#/block/11680482
```

- inline_transfer opeation
```
op id: 78
inline_transfer  block: 11680482
https://testnet.wallet.gxchain.org/#/account/bb11/overview
```

operations:
https://github.com/gxchain/gxb-core/blob/dev_master/libraries/chain/include/graphene/chain/protocol/operations.hpp#L138

**Comment by lanhaoxiang** [comment]
done by 89a9bf78fa52e31d98b29428ef76a88421ef9113
